//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from HemoParser.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="HemoParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public interface IHemoParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="HemoParser.compilationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompilationUnit([NotNull] HemoParser.CompilationUnitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HemoParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] HemoParser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HemoParser.nullLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNullLiteral([NotNull] HemoParser.NullLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HemoParser.booleanLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBooleanLiteral([NotNull] HemoParser.BooleanLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HemoParser.integerLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntegerLiteral([NotNull] HemoParser.IntegerLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HemoParser.decimalIntegerLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDecimalIntegerLiteral([NotNull] HemoParser.DecimalIntegerLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HemoParser.hexadecimalIntegerLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHexadecimalIntegerLiteral([NotNull] HemoParser.HexadecimalIntegerLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HemoParser.octalIntegerLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOctalIntegerLiteral([NotNull] HemoParser.OctalIntegerLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HemoParser.binaryIntegerLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinaryIntegerLiteral([NotNull] HemoParser.BinaryIntegerLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HemoParser.realLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRealLiteral([NotNull] HemoParser.RealLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HemoParser.characterLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCharacterLiteral([NotNull] HemoParser.CharacterLiteralContext context);
}
